name: Deploy to Google Cloud VM

on:
    push:
        branches:
            - master # Hoặc 'master' tùy tên nhánh chính của bạn

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: 22
                  script: |
                      # 1. Vào thư mục
                      cd ~/be-swp391-eye-wear

                      # 2. Lấy code (SỬA main THÀNH master NẾU CẦN)
                      git fetch origin
                      git pull origin master 

                      # 3. Chạy Docker (QUAN TRỌNG: ĐÃ XÓA CHỮ SUDO Ở ĐẦU)
                      docker compose up -d --build

                      # 4. Dọn dẹp (QUAN TRỌNG: ĐÃ XÓA CHỮ SUDO Ở ĐẦU)
                      docker image prune -f
